spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

keycloak:
  base-url: http://keycloak:8080
  realm: master
  admin-username: ${KEYCLOAK_ADMIN}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}