services:
  task-service:
    build: task-service
    container_name: task-service
    depends_on:
      - task-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task-db:5432/task_service
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    expose:
      - "8080"

  auth-service:
    build: auth-service
    container_name: auth-service
    depends_on:
      - keycloak
      - kafka
    environment:
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    expose:
      - "8080"

  api-gateway:
    build: api-gateway
    container_name: api-gateway
    depends_on:
      - auth-service
      - task-service
      - accounting-service
    ports:
      - "8082:8080"

  accounting-service:
    build: accounting-service
    container_name: accounting-service
    depends_on:
      - accounting-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounting-db:5432/accounting_service
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "8080"